### ISSUE TITLE
浏览模式图片显示不全的问题

### ISSUE THREAD

**Issue by Azukio1994** [coderzhaoziwei/yande-re-chinese-patch#10]
在普通模式下有某张图片，点进浏览模式后没有
浏览器是edge
![image](https://user-images.githubusercontent.com/88309278/133571810-9a8b31ce-5af9-44ef-bc3a-51a0dc8660bc.png)
![image](https://user-images.githubusercontent.com/88309278/133571860-2ba69e01-51ec-41bc-a430-0e64917fc007.png)

**Comment by fullmooooon** [comment]
浏览模式下是调用接口显示图片，和默认的显示图片是有一些区别的。

比如一个图片记录刚刚上传，图片信息还没完全编辑发布，默认是不会显示的，但是会出现浏览模式里面。
比如一张较早的图片记录被编辑，一个列表获取会更新它的位置，而另一个不会。（你这个就属于这个情况，你没找到的那张图片跟排在它旁边的图片上传时间差了很久）
