### ISSUE TITLE
【需求】鼠标中键新标签页中打开链接。

### ISSUE THREAD

**Issue by dyguests** [coderzhaoziwei/yande-re-chinese-patch#11]
1、鼠标中键新标签页中打开链接。
     通常浏览器均有该功能，但是在插件下中键没有这个功能。
2、单图预览时，详情等信息可以放在图片外侧，而不是在图片中吗？

**Comment by coderzhaoziwei** [comment]
1、鼠标中键单击链接（通常是  `<a>` 标签）打开新标签是浏览器的功能，你所说的「插件下中键没有这个功能」是指使用鼠标中间单击页面的什么元素？
2、无限浏览模式的单图预览窗口中，单击图片可以隐藏详情。这应该是一个设计方面的问题，我当初关注的是手机屏幕本身不大，单击切换显隐应该算是最简单的方式了？
