### ISSUE TITLE
镜像站无法打开

### ISSUE THREAD

**Issue by faust213** [coderzhaoziwei/yande-re-chinese-patch#19]
oreno.imouto.us无法打开yande.in说host错误。 yande.re可以科学上网打开，请问还有别的办法不用科学上网打开吗

**Comment by fullmooooon** [comment]
好心人做的镜像站，哪天没了也正常
yande.re 还能改 host 上，不过加载速度没有当初没被盯上时能裸连爽

**Comment by dragonxash** [comment]
> 好心人做的镜像站，哪天没了也正常 yande.re 还能改 host 上，不过加载速度没有当初没被盯上时能裸连爽

大佬host文件来一个

**Comment by coderzhaoziwei** [comment]
脚本支持站点已删除 `oreno.imouto.us`。
