### ISSUE TITLE
y站的浏览模式不能下载图片

### ISSUE THREAD

**Issue by jojo521111** [coderzhaoziwei/yande-re-chinese-patch#20]
y站的浏览模式不能下载图片，之前有个k站类似的那个问题有解决方法但是没看懂，我不知道解决方法是否类似，求大佬指点。感谢！

**Comment by asadahimeka** [comment]
跨域问题因为浏览器安全限制单纯通过页面 js 来解决是挺困难的，可以考虑调用扩展的能力来实现，如 [https://www.tampermonkey.net/documentation.php#GM_download](GM_download) 所说，Tampermonkey 提供了一个 `GM_download` 方法可以用来下载文件，如果不考虑其他类型的脚本扩展的话可以试下这个
![2022-4-17 12-51-30](https://user-images.githubusercontent.com/31837214/163701061-398a4549-411b-42ff-9346-18d9467c4a9b.png)
![2022-4-17 12-33-26](https://user-images.githubusercontent.com/31837214/163701067-34b2dbea-6af1-4ccb-ac6a-96e909c1c248.png)
![2022-4-17 12-31-28](https://user-images.githubusercontent.com/31837214/163701070-c4ab76ee-6114-4985-8849-6012a3a5d53a.png)
![2022-4-17 12-47-39](https://user-images.githubusercontent.com/31837214/163701071-607c6a57-0a21-498a-afc0-7ae2d9b33638.png)

**Comment by coderzhaoziwei** [comment]
妙啊。

我平时做前端开发，一直局限在 js 里面想办法，忘了 Tampermonkey 直接提供了一些 node 的能力，所以觉得这个问题挺无解的。

我这就去更新，谢谢啊！ @asadahimeka
