### ISSUE TITLE
关于浏览模式下 Post 收藏状态的查询

### ISSUE THREAD

**Issue by asadahimeka** [coderzhaoziwei/yande-re-chinese-patch#25]
最近查阅 [moebooru](https://github.com/moebooru/moebooru/) 源码得知，可通过指定 API 版本并配合参数 `include_votes=1` 实现查询 Post 的 vote 信息。
那么是否可以通过比如这个请求 https://yande.re/post.json?api_version=2&include_votes=1 来实现 Post 收藏状态的查询呢

![image](https://user-images.githubusercontent.com/31837214/177030639-db8ad27a-7a50-4e64-a1b3-1f4ec96b5b1e.png)

#18

**Comment by coderzhaoziwei** [comment]
好像不行。

**Comment by coderzhaoziwei** [comment]
（我也没仔细看）

主要是因为这个接口，一没有指定用户，二没有指定作品，所以大概是不行。

**Comment by coderzhaoziwei** [comment]
噢，我懂你意思了，这个接口是请求作品列表的时候就拿到收藏的数据是吧？默认请求40个，能知道40个里哪些是已经收藏的。

那应该是可以了。我之前还在想指定作品会不会有什么接口。

**Comment by asadahimeka** [comment]
> （我也没仔细看）
> 
> 主要是因为这个接口，一没有指定用户，二没有指定作品，所以大概是不行。

用户是 cookie 里指定的，就是这个 votes 里是当前用户对 posts 的投票信息，3 的话应该就是收藏了吧
![image](https://user-images.githubusercontent.com/31837214/177044418-c914104b-c9b1-4b97-b91b-d49863edbb66.png)

如果要指定作品好像也可以，配合 tags 语法，比如这样 https://yande.re/post.json?api_version=2&include_votes=1&tags=id:994595 ，未收藏的话 votes 就应该是 `{}` 吧

**Comment by asadahimeka** [comment]
另外发现 moebooru 好像自带中文界面翻译，设置查询参数 `locale=zh_CN` 就行，比如 https://yande.re/post?locale=zh_CN

![image](https://user-images.githubusercontent.com/31837214/177044928-0f4ebc6b-eb4c-4b95-a835-f97b2dd6031e.png)
![image](https://user-images.githubusercontent.com/31837214/177044936-d3729be3-7a56-4f76-89ca-1844749a5eae.png)

**Comment by coderzhaoziwei** [comment]
这个参数 `tags=id:POST_ID` 确实有用，啊很方便了。

**Comment by coderzhaoziwei** [comment]
哎，我看你最后一张截图 `/static/more` 这个路径下没带参数也显示的中文。

在工作，不适合打开这个站，就先不看了哈。

**Comment by asadahimeka** [comment]
> 哎，我看你最后一张截图 `/static/more` 这个路径下没带参数也显示的中文。
> 
> 在工作，不适合打开这个站，就先不看了哈。

好像是用参数访问过一次后会存到 cookie 里，之后访问就不用带参数了
