### ISSUE TITLE
关于几个条目的翻译补充

### ISSUE THREAD

**Issue by NightSharp** [coderzhaoziwei/yande-re-chinese-patch#27]
## 图片 1
![01](https://user-images.githubusercontent.com/9748063/182021973-5c2f43f1-b0f4-41ab-9d2a-9d4c4cb61d77.png)
```
Pools = 图集
Wiki = 百科
```

## 图片 2
![02](https://user-images.githubusercontent.com/9748063/182021974-98a964ac-86af-44a2-a4a9-c83d29b2ba1e.png)
```
Search = 搜索
Tags = 标签
Statistics = 数据信息
Posted = 投稿于
%d days ago = %d 天前，
by %u = 投稿用户为 %u
Size = 尺寸
Source = 来源
Rating = 评级
Questionable = 存疑
Score = 点数
Favorited = 收藏用户
%d more = 还有 %d 位
Options = 选项
Edit = 编辑
Flag for deletion = 标记为删除
Add translation = 添加翻译
Post history = 投稿历史记录
Related Posts = 相关投稿
Previous = 上一张
Next = 下一张
Parent = 父作品
Random = 随机
```

## 图片 3
![03](https://user-images.githubusercontent.com/9748063/182021976-c9deb88c-d6f1-4847-b92e-cc2a77dbb207.png)
```
Previous = 上一张
Next = 下一张
This post is #%n in the %s pool. = 此投稿是 %s 图集中的第 %n 张作品。 
```

## 图片 4
![04](https://user-images.githubusercontent.com/9748063/182021978-09d60d6a-a53a-4aa5-861f-bac1206e8f08.png)
```
This post was deleted. Reason = 此投稿被删除了。原因
upscale of %d. MD5 = 大小超过了 %d 。MD5值
```

**Comment by coderzhaoziwei** [comment]
啊，我之前还以为你是要补充 tags 的翻译。页面的翻译之前已经有朋友找到方法了，等我有空实装一下。

**Comment by coderzhaoziwei** [comment]
手动翻译页面上的这些元素其实很不划算，因为每个替换都得专门写。项目之初我也是只做 tags 的翻译来着。

**Comment by coderzhaoziwei** [comment]
最新版会自动设置 cookie 为简体中文了。

**Comment by NightSharp** [comment]
> 最新版会自动设置 cookie 为简体中文了。

那个 Rating 翻译成 评级 感觉更合适呀

另外发现了几个新项
![屏幕截图 2022-08-11 123852](https://user-images.githubusercontent.com/9748063/184065766-6a03cc21-9cb3-4da3-b967-444a2fe69fbc.png)
![屏幕截图 2022-08-11 123918](https://user-images.githubusercontent.com/9748063/184065780-cf9a9eaf-5198-4d50-b600-91d5e6e81d24.png)

**Comment by coderzhaoziwei** [comment]
目前的用户界面，脚本没有做翻译的事情，只是帮用户自动使用了 moebooru 框架自带的简体中文。

想把所有的英语都翻译的话比较麻烦，不太值得花这个时间。

这个脚本暂时只翻译标签词条。

**Comment by NightSharp** [comment]
好吧
