### ISSUE TITLE
请问可以增加一个大图样式吗？

### ISSUE THREAD

**Issue by KanaBackyard** [coderzhaoziwei/yande-re-chinese-patch#3]
类似这个脚本提供的功能
https://github.com/mouyase/yande.re_large_picture_script
现在的样式把图片都压缩成方形，有些长图没法预览全图要点进去才能看挺麻烦的，谢谢

**Comment by coderzhaoziwei** [comment]
试一试网站自带的 browse 模式？

**Comment by coderzhaoziwei** [comment]
搞定了。

除了大图模式，我还添加了高清模式。你可以试试看效果，有 BUG 的话可以再留言。

**Comment by KanaBackyard** [comment]
感謝大佬！

**Comment by KanaBackyard** [comment]
不好意思，大佬我又来了~
我看到代码里写的是使用方向键来进行翻页操作。
请问我想自己修改成如下快捷键的话需要修改那些内容呢？
加入快捷键操作，按下 ← 或 A 上一页，按下 → 或 D 下一页，按下 S 或 O 查看原图，按下 F 查看来源页面
（因为左手操作键盘，右手鼠标操作比较符合习惯，而且存图的alt+s也在左边比较方便）
其次就是想问下后期会不会考虑增加konachan和danbooru的支持呀

**Comment by coderzhaoziwei** [comment]
1、键盘事件？站点源码已经加载了 jQuery，你要是会用 jQuery 的话很简单。

2、yande、konachan、danbooru 都很像，等有空适配一下。

**Comment by coderzhaoziwei** [comment]
发布了 2.0 版本，用 Vue 做了个浏览模式，移动端舒服了。电脑的话，新的浏览模式下，只用鼠标也比原来省事儿很多。

**Comment by KanaBackyard** [comment]
好的~

**Comment by KanaBackyard** [comment]
https://i.loli.net/2021/05/16/Pry3j6dEHTVJRIg.png
我现在用的是这个。
我自己去修改快捷键把Arrowleft修改成A好像也没用

**Comment by coderzhaoziwei** [comment]
现在支持 K 站了！

---

虽然 moebooru 最初就是由 danbooru 的代码修改而来，但是经过了长期的更新迭代，这两个图站的前端代码差异还是挺大的，因此本项目应该是无法适配使用 danbooru 的站点了。

konachan.com 与 yande.re 的服务端都使用了 moebooru，前端代码的差别不大，微调了下就可以很好的使用了。

**Comment by coderzhaoziwei** [comment]
关于绑定键盘事件的需求，有时间我会适配上。

**Comment by KanaBackyard** [comment]
谢谢大佬~
