### ISSUE TITLE
请问大大可以考虑加入一个gelbooru的版本吗？

### ISSUE THREAD

**Issue by Azukio1994** [coderzhaoziwei/yande-re-chinese-patch#4]
这些插件就您的这个最好用，要是能匹配一下这个图站，无敌了！
域名：https://gelbooru.com/index.php?page=post&s=list&tags=all

**Comment by coderzhaoziwei** [comment]
Y 站和 K 站 的前端代码几乎一样，所以微调一下很容易就兼容了。这个站 gelbooru 用的是框架的另一个分支，虽然前端看上去也有些像，但是代码层面已经是不一样的了。所以 gelbooru 的版本，就需要单独另写一个插件才行。

**Comment by Azukio1994** [comment]
噢噢~~原来如此...那太麻烦了~！我还以为也差不多呢~哈哈哈~~谢谢大大回复~

**Comment by asadahimeka** [comment]
> 这些插件就您的这个最好用，要是能匹配一下这个图站，无敌了！ 域名：https://gelbooru.com/index.php?page=post&s=list&tags=all

@Azukio1994  如果只是用瀑布流功能的话，可以用我这个凑活一下：https://greasyfork.org/zh-CN/scripts/444885
