### ISSUE TITLE
直接在图片页面添加下载

### ISSUE THREAD

**Issue by wnxdzh** [coderzhaoziwei/yande-re-chinese-patch#5]
非常感谢您的分享

  进入浏览模式，单图预览会浮现聚合详情，然后就可以下载此图片。那么是否可以添加一个选项，直接在未进入浏览模式的情况下显示下载原文件或高清图选项，更方便下载。

**Comment by coderzhaoziwei** [comment]
未进入浏览模式时，网站原本的左栏中就已经有直接下载原图的选项。例如：

```
显示高清图
下载高清图 (562 KB JPG)
下载 PNG 图 (3.46 MB)
```
