### ISSUE TITLE
W快捷键导致循环弹窗

### ISSUE THREAD

**Issue by shirakagi** [coderzhaoziwei/yande-re-chinese-patch#7]
浏览器ctrl+W是关闭标签页
显示当前作品来源：W
也是W键 就会导致关闭弹窗来源 时继续弹窗导致无限循环
希望调整此快捷键  或者关闭此快捷键

**Comment by coderzhaoziwei** [comment]
浏览器：Edge 92.0.902.73

我刚刚自己试了一下，无法重现你的问题。
