### ISSUE TITLE
兼容danbooru网站

### ISSUE THREAD

**Issue by number-four-dj** [coderzhaoziwei/yande-re-chinese-patch#8]
大佬，能不能再兼容下 https://danbooru.donmai.us/ 这个网站，你的插件用了后，别的插件都用不习惯了，能不能考虑兼容下，网站风格差不多，感谢

**Comment by coderzhaoziwei** [comment]
站点代码差距较大，无法兼容。

**Comment by asadahimeka** [comment]
> 大佬，能不能再兼容下 https://danbooru.donmai.us/ 这个网站，你的插件用了后，别的插件都用不习惯了，能不能考虑兼容下，网站风格差不多，感谢

如果只是用瀑布流功能的话，可以用我这个凑活一下：https://greasyfork.org/zh-CN/scripts/444885
