### ISSUE TITLE
2.0.69 tag + - 重复注释

### ISSUE THREAD

**Issue by rcyggdra** [coderzhaoziwei/yande-re-chinese-patch#9]
![image](https://user-images.githubusercontent.com/8652464/132167353-b9043fdf-0506-49dd-b3be-c6c7b384d02e.png)
如图，画师、原作、角色的+-号前有重复，影响直观。

**Comment by coderzhaoziwei** [comment]
我在脚本关闭的情况下，正常访问 `https://yande.re/post`，没有发现 tag 左侧有加减符号。

**Comment by rcyggdra** [comment]
> 我在脚本关闭的情况下，正常访问 `https://yande.re/post`，没有发现 tag 左侧有加减符号。

请登录yande.re账户才有tag的加减符号；v2.0.68无此问题。

**Comment by coderzhaoziwei** [comment]
我登录账号检查了，确实有问题。刚刚修复，已经更新至 `2.0.71` 版本。
